export const RECEIVE_PEOPLES = 'RECEIVE_PEOPLES'
export const SET_FILTER_PEOPLES = 'SET_FILTER_PEOPLES'
export const RESET_FILTER_PEOPLES = 'RESET_FILTER_PEOPLES'
export const UPDATE_AGE_OF_PEOPLE = 'UPDATE_AGE_OF_PEOPLE'
